{{- if and .Values.config.webhooksEnabled .Values.certgen.serviceAccount.create (not .Values.certManager.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rig-operator.certgen.serviceAccountName" . }}
  labels: {{ include "rig-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
{{- end -}}
