{{- if and .Values.config.webhooksEnabled .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rig-operator.apicheck.fullname" . }}
  labels: {{ include "rig-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
  - apiGroups: ["rig.dev"]
    resources: ["capsules"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rig-operator.apicheck.fullname" . }}
  labels: {{ include "rig-operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rig-operator.apicheck.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rig-operator.apicheck.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
