apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rig-platform.fullname" . }}-config
  labels: {{ include "rig-platform.labels" . | nindent 4 }}
data:
  config.yaml: | {{ include "rig-platform.config" . | nindent 4 }}
