{{- if not .Values.secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rig.fullname" . }}
  labels: {{ include "rig.labels" . | nindent 4 }}
data:
  server-config.yaml: {{ include "rig.config" . | b64enc }}
{{- end -}}
